### ISSUE TITLE
No TOTP found for entry but clicking another entry gives correct TOTP

### ISSUE THREAD

**Issue by fnadde42** [keepassxreboot/keepassxc-browser#1303]
## Expected Behavior

When I select an entry from the plugin icon in the top right I expect that entry to be pasted. Same goes for TOTP pasting. Watch the attached video.

## Current Behavior

When I select an entry from the plugin icon in the top right it gives me another one. See video.

## Steps to Reproduce (for bugs)

1. I connected two databases
2. I went in on GitHub
3. Three entries popped up and I clicked on the plugin icon in the top right and selected the one I wanted
4. The wrong credentials got pasted in the login form

### Demo

In the end the TOTP code that got pasted worked, even though the browser plugin claimed it was for another entry.

https://user-images.githubusercontent.com/1107419/114268280-970fba80-9a00-11eb-8cb2-ee363cb4e51b.mp4

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: macOS Catalina 10.15.7
Browser: Firefox 87.0

I have two databases connected with two different unique identifiers.

**Comment by varjolintu** [comment]
Already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1296. Use the input field icon instead while waiting for the next release.

**Comment by fnadde42** [comment]
I have tried the latest release 1.7.8 and the problem with not finding the OTP still persist. As you can see in the video I have an OTP code for the entry I'm loggning in with but when I come to the OTP window and try to paste the OTP it says that it can't be found. If I THEN select the last entry in the list (when you click on the browser add-on icon) I can suddenly paste an OTP code. That entry isn't even configured with OTP and when I try to log in I succeed. That means that the OTP code exists in another entry.

**Comment by droidmonkey** [comment]
That problem was recently fixed due to sorting error

**Comment by fnadde42** [comment]
Okay but I'm running the newly released 1.7.8 and I still get that problem. Is the fix in this release or in a future release?

**Comment by droidmonkey** [comment]
@varjolintu did we miss a spot where sorting can fail us?

**Comment by varjolintu** [comment]
@droidmonkey The fix was made after 1.7.8. I can release a 1.7.8.1 for a quick fix.

**Comment by droidmonkey** [comment]
Gotcha it was marked under the 1.7.8 milestone was confused. We should release a small update.
