### ISSUE TITLE
Credential fields not auto-filling

### ISSUE THREAD

**Issue by tfvlrue** [keepassxreboot/keepassxc-browser#187]
## Expected Behavior
I have the "Automatically fill-in single credentials entry." setting enabled.
In 1.1.2, credential fields for all websites would automatically fill in. This is the expected behavior.
In 1.1.3, occasionally fields would fail to be detected. I worked around this by clicking the "Redetect Credential Fields" button, and it would fill in the fields.

## Current Behavior
As of 1.1.4, many websites do not auto-fill, and clicking the "Redetect" button fails to do anything.
Fields simply are not auto-filled and there doesn't seem to be a way to get them to fill. The username picker is also not appearing when clicking in the username box.
Additionally, sometimes the page becomes unresponsive and Firefox shows a yellow bar explaining the keepassxc-browser add-on is slowing down the page. (Clicking "Stop" makes the page interactive again.)

## Possible Solution
This is a regression that has started in 1.1.3 and got significantly worse in 1.1.4.

## Steps to Reproduce (for bugs)
Here are a few examples of sites which worked in 1.1.3 but no longer work in 1.1.4:

1. https://www.ally.com/
2. https://nb.fidelity.com/public/nb/default/home
3. https://verified.capitalone.com/sic-ui/#/esignin

Let me know if there is any more info I can provide.

Edit: One more piece of info, not sure if useful. As soon as I reverted to version 1.1.3, all of the credential fields in the tabs I had open immediately got filled in, without refreshing the page or anything.

## Debug info
KeePassXC - 2.39
keepassxc-browser - 1.1.4
Operating system: Win
Browser: Firefox 60.0.2 (64-bit)
Proxy used: NO

**Comment by varjolintu** [comment]
Indeed the autofill is doing something strange. I'm on it.

**Comment by varjolintu** [comment]
This is related to the new MutationObserver changes. In the meantime a workaround is to disable auto-fill.

**Comment by cryptomilk** [comment]
I do not use 'auto-fill' of credentials, I have just ticked auto-retrieve. However when clicking on the username field normally you can select the credentials but this does not work. It looks like that the credential field detection doesn't work at all.

**Comment by varjolintu** [comment]
@cryptomilk That bug is a different issue and has been fixed. A release is soon.

**Comment by tfvlrue** [comment]
I installed version 1.1.5, but I could not get it to connect to the KeePass database. Then I installed 1.1.6 and this problem still exists, and the Redetect Credential Fields button continues to have no effect on it. Is there any more information I can provide to help debug this? It's a 100% repro for me, on the sites I mentioned above.

**Comment by tfvlrue** [comment]
This appears to be fixed with 1.1.7. Thanks!
