### ISSUE TITLE
v1.1.4 does not work (UI anymore) at all

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#192]
## Expected Behavior

Work as usual…

## Current Behavior

The UI state is complexly broken.
The **only way** inserting usernames/password works is when by right-clicking on the input field and choosing "add username/password" or similar.

It does not:
* show the key next to the password field
* show any passwords in the popup (always only lets me click "recheck credential fields")
* show any dropdown when clicking into username/pw fields

This happens on all sites.

I hope it is related, but it also does not show me the actual KeePassXC-browser version:

![grafik](https://user-images.githubusercontent.com/11966684/41251627-c49c8f16-6dba-11e8-9078-581b1f945474.png)

Some logs here:
<details>

``` 
TypeError: cip.settings.ignoredSites is not iterable keepassxc-browser.js:1350:1
20:55:51.561 Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert. (unbekannt)
20:55:51.652 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (NAVIGATOR, OBJECT) {

    OBJ....  keepassxc-browser:1
20:55:51.652 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (ERROR) {

    const V8_STACK_....  keepassxc-browser:1
20:55:52.069 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  webrequest.js:118
	onBeforeRequest moz-extension://48e8a53b-891a-424d-881d-0c47a6d247cc/js/webrequest.js:118:3
20:55:52.114 TypeError: cip.settings.ignoredSites is not iterable keepassxc-browser.js:1350:1
20:55:53.554 Error: WebExtension context not found!  ExtensionParent.jsm:861:13
20:55:53.591 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (NAVIGATOR, OBJECT) {

    OBJ....  releases:1
20:55:53.591 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: (function (ERROR) {

    const V8_STACK_....  releases:1
20:55:53.971 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  webrequest.js:118
	onBeforeRequest moz-extension://48e8a53b-891a-424d-881d-0c47a6d247cc/js/webrequest.js:118:3
20:55:54.051 TypeError: cip.settings.ignoredSites is not iterable  keepassxc-browser.js:1350:1
20:56:36.745 Webconsole context has changed
20:57:03.330 Error 1: Datenbank nicht geöffnet  keepass.js:976:5
20:57:04.686 Error 1: Datenbank nicht geöffnet keepass.js:976:5
20:57:05.525 [Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no]  (unbekannt)
20:57:11.007 TypeError: cip.settings.ignoredSites is not iterable  keepassxc-browser.js:1350:1
20:57:18.119 TypeError: cip.settings.ignoredSites is not iterable  keepassxc-browser.js:1350:1
20:57:19.885 this._recipeManager is null  LoginManagerParent.jsm:84
20:57:19.899 Invalid chrome URI: /
20:57:21.827 Error 14: Keine URL angegeben  keepass.js:976:5
20:57:21.861 TypeError: cip.settings.ignoredSites is not iterable keepassxc-browser.js:1350:1
20:57:25.242 Error: WebExtension context not found!  ExtensionParent.jsm:861:13
20:57:25.639 TypeError: cip.settings.ignoredSites is not iterable  keepassxc-browser.js:1350:1
20:57:25.987 Promise rejected after context unloaded: Promised response from onMessage listener went out of scope
  keepassxc-browser.js:1496
20:57:25.987 Promise rejected after context unloaded: Promised response from onMessage listener went out of scope
  keepassxc-browser.js:1730
20:57:25.987 Promise rejected after context unloaded: Promised response from onMessage listener went out of scope
  keepassxc-browser.js:1739
20:58:19.930 TypeError: cip.settings.ignoredSites is not iterable keepassxc-browser.js:1350:1
``` 
</details>

## Possible Solution

Can you recall that release?

As for the cause, I guess the content scripts are just broken.

## Steps to Reproduce (for bugs)

Connect as usual. I first thought it is one of the usual issues, but I tried:
* restarting browser
* locking database and unlocking it (note that this works correctly and the popup also updates it's state correctly)
* locking database, open popup (so it notices it is locked), and unlock it

## Debug info

KeePassXC - Version 2.3.3
Revision: 0a155d8
Operating system: Linux, Fedora 28
Browser: Firefox 60
Proxy used: yes

And next time, better release a beta version first, or so… :wink:

**Comment by rask** [comment]
Same issue here. Latest Chromium on Ubuntu 17.10.

**Comment by varjolintu** [comment]
Did you upgrade to 1.1.5? It should solve this issue.

**Comment by noone-silentrunner** [comment]
Still exists. Maybe code breaks on this line:

```
// From Chrome Plugin
Uncaught (in promise) TypeError: cip.settings.ignoredSites is not iterable
    at browser.runtime.sendMessage.then (keepassxc-browser.js:1377)
```

I get this everytime I hover anything form related or onload

**Comment by rask** [comment]
I tried adding a dummy URL to the ignored sites list setting but the `iterable` error still appears.

**Comment by varjolintu** [comment]
I added a check for that but it seems I missed one.

**Comment by cryptomilk** [comment]
1.1.5 does not solve the issue. The plugin doesn't detect the input fields at all. I hope that #196 fixes it :-)
