### ISSUE TITLE
"Fill Password Only" not working

### ISSUE THREAD

**Issue by icamps** [keepassxreboot/keepassxc-browser#2135]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
There are some authentication pages in my university that blocked the possibility to add both login/pass in the authentication pages. After that blocking, I add the login info first, and then, after going to `Fill Password Only`, I could add the corresponding password.

Since few days ago, after doing the process describer above, I am getting the error message:

`Filling password to a plain text field is prevented.`

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a page where login/password input is blocked.
2. Add only the login info.
3. Go to `Fill Password Only` and try to add the password only.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected that the password is injected in the text field as previously.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password in not injected and an error message appear:

`Filling password to a plain text field is prevented.`

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am using the Brave v1.63.165 (Feb 28, 2024)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by varjolintu** [comment]
Choose the input field manually using Custom Login Fields to override this.

**Comment by hazelnot** [comment]
> Choose the input field manually using Custom Login Fields to override this.

This doesn't work either. I set and saved the custom password field, but it's still not detected nor does it allow me to enter password only. This is happening on Firefox 123 on Arch Linux.

**Comment by Flamefire** [comment]
Same here (Firefox on Windows)

The particular input form has an option to show/hide the password which changes the input-type attribute. I guess this confuses the extension and there is no way to make it still put in the password even when explicitely requested to do so. An option to allow this is hence required.

**Comment by xxyxxyxyx1** [comment]
I also have the same problem. I chose the input field manually using custom login fields, but I still get the same "Filling password to plain text field is prevented" error. I'm using Firefox 126 on macOS. 

@varjolintu this issue should be reopened, the posted solution does not resolve the problem for multiple people.

**Comment by varjolintu** [comment]
Reopened. Can you give my sites where this happens? I have tested this locally and with multiple pages, and I have no issues if I select the password field using Custom Login Fields.

**Comment by xxyxxyxyx1** [comment]
Thank you for reopening. 

Unfortunately I cannot provide a link to a site on the public internet where I have this problem. I experience it in two cases:
- a site within my employer's private intranet, which might be designed weirdly
- controlling networked computers using [cockpit](https://cockpit-project.org/), which provides a terminal in the web browser. I often need to enter a password for `sudo` commands, and it would be much better to do this with a keyboard shortcut and the browser plugin, instead of copy/pasting from the main keepassxc application.

**Comment by varjolintu** [comment]
I think one solution would be to add a separate option for this in the extension settings. Users could disable this check if they want to. There might be cases where entering the password to a plain-text field is needed but Custom Login Fields might not work in that scenario.

**Comment by xxyxxyxyx1** [comment]
That sounds good to me. 
It could be added as a field in the "Site preferences" table, so it applies only to certain sites. It seems like an uncommon option that should only be enabled exactly where necessary, with the user understanding what they are doing.

**Comment by icamps** [comment]
> I think one solution would be to add a separate option for this in the extension settings. Users could disable this check if they want to. There might be cases where entering the password to a plain-text field is needed but Custom Login Fields might not work in that scenario.

That sounds good to me too.

**Comment by walkeral** [comment]
I've hit this problem as well, however there is something interesting about this particular site (British Gas).
On any "working" site I can go "Choose a Custom Login Field", then click "Password", and I can see a grey shading box over the password field with "Password" in it. This also works fine on sites with separate pages for username and password (like Box).
On this non-functioning site I get nothing at all, like it can't even see the field is there. I did have to enable "Allow Cross-Origin iframes" when I selected the username (this site does use separate pages for username and password).

**Comment by Flamefire** [comment]
> On any "working" site I can go "Choose a Custom Login Field", then click "Password", and I can see a grey shading box over the password field with "Password" in it. This also works fine on sites with separate pages for username and password (like Box).
On this non-functioning site I get nothing at all, like it can't even see the field is there

That's the same for me: It doesn't let me choose neither the username nor the password field on affected pages, i.e. no (in my case violet) shading with the text when hovering over the fields after clicking one of the manual select buttons

**Comment by JasonSome** [comment]
Reporting that this is still not working, and an example website is Chase's secure websites (not all of them, but whichever ones have a "Show" right next to the Password field).

**Comment by Malkierian** [comment]
Was just coming here about Chase myself. Same experience as JasonSome.
https://secure07c.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/index

**Comment by varjolintu** [comment]
> Was just coming here about Chase myself. Same experience as JasonSome. https://secure07c.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/index

This happens because the actual input is wrapped inside an element that steals the `document.activeElement`. The extension cannot know that you meant to select the actual child input.

**Comment by ginkel** [comment]
I've got another page where this happens: https://business.ing.de/login/

**Comment by varjolintu** [comment]
> I've got another page where this happens: https://business.ing.de/login/

This is not related to this issue at all. The input field is just not detected because.. there's a form, which has iframe inside it, and a `document` element inside that one.. Phew.

**Comment by varjolintu** [comment]
>     2. cloud.pocketbook.digital password-only page used to login: https://cloud.pocketbook.digital/browser/en

This is not related to this issue at all. The input field is just not detected because.. there's a form, which has `iframe` inside it, and a `document` element inside that one.. Phew.

**Comment by varjolintu** [comment]
Just a reminder, that please read the issue description before commenting about issues that are not related. It makes my job easier.

**Comment by ginkel** [comment]
> > I've got another page where this happens: https://business.ing.de/login/
> 
> Not related to this issue either. The input elements are inside a nested Shadow DOM elements which we support only partially.

I'm sorry for not analyzing the cause before commenting. Would you like me to open a new issue or do you consider this broken beyond repair?

**Comment by varjolintu** [comment]
> > > I've got another page where this happens: https://business.ing.de/login/
> > 
> > 
> > Not related to this issue either. The input elements are inside a nested Shadow DOM elements which we support only partially.
> 
> I'm sorry for not analyzing the cause before commenting. Would you like me to open a new issue or do you consider this broken beyond repair?

The correct place for these kind of detection issues is the dedicated pinned issue: https://github.com/keepassxreboot/keepassxc-browser/issues/1358

**Comment by varjolintu** [comment]
I made a simple fix for this. Give it a try if you can :)

**Comment by icamps** [comment]
> I made a simple fix for this. Give it a try if you can :)

In version 1.9.1? If yes, here the problem remains.

**Comment by varjolintu** [comment]
@icamps No. The linked pull request has it.

**Comment by icamps** [comment]
> @icamps No. The linked pull request has it.

Sorry my ignorance, but how do I test it?

**Comment by pzystorm** [comment]
> One site where I found is the login site of https://www.payback.de
> 
> The "password" field looks odd:

https://www.payback.de is still not working. The username works. But the password not. It seems somehow related to ifames and the Google Recaptcha thingy which is at the bottom right of that page. Because whenever i try to fill in a password via KeePassXC magic, there is INSIDE this small Google recaptcha box a message from KeePassXC, that no passwords for www.google.com has been found.

Could you have a look?

**Comment by icamps** [comment]
Any update?

**Comment by droidmonkey** [comment]
What's to update? This feature works fine

**Comment by icamps** [comment]
From this side it is not working as it keeps complaining about plain password input.
![WhatsApp Image 2024-10-01 at 16 47 31](https://github.com/user-attachments/assets/daafa46b-92e1-41d8-ad8f-b0327311e5f1)

**Comment by droidmonkey** [comment]
Make sure your extension is updated, this was fixed in version 1.9.2

**Comment by varjolintu** [comment]
Selecting the field manually using Custom Login Fields also removes that restriction.

**Comment by pzystorm** [comment]
Only on www.payback.de it is still broken. Although using v1.9.3 keepassxc always tries to find fields in the Google recaptcha window at the bottom right - and not in the main window. Shall I open a new bug for this?

**Comment by patja** [comment]
Not fixed for login fields on [Verity Credit Union](https://secure.veritycu.com)

Cannot select fields for custom login fields.  The confirm button is never enabled when selecting custom login fields.

**Comment by varjolintu** [comment]
> Not fixed for login fields on [Verity Credit Union](https://secure.veritycu.com)
> 
> Cannot select fields for custom login fields. The confirm button is never enabled when selecting custom login fields.

Are you sure this is related to this thread?

**Comment by patja** [comment]
> > Not fixed for login fields on [Verity Credit Union](https://secure.veritycu.com)
> > Cannot select fields for custom login fields. The confirm button is never enabled when selecting custom login fields.
> 
> Are you sure this is related to this thread?

No I'm not sure.  Maybe it is different because I never see any error message about plain text fields.  I do know that nothing happens when I select "Fill Password Only", and I am also unable to specify any custom login fields for this site.  My only option is to manually copy and paste the password.

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Win64
Browser: Mozilla Firefox 131.0

**Comment by varjolintu** [comment]
> > > Not fixed for login fields on [Verity Credit Union](https://secure.veritycu.com)
> > > Cannot select fields for custom login fields. The confirm button is never enabled when selecting custom login fields.
> > 
> > 
> > Are you sure this is related to this thread?
> 
> No I'm not sure. Maybe it is different because I never see any error message about plain text fields. I do know that nothing happens when I select "Fill Password Only", and I am also unable to specify any custom login fields for this site. My only option is to manually copy and paste the password.
> 
> KeePassXC - 2.7.9 KeePassXC-Browser - 1.9.3 Operating system: Win64 Browser: Mozilla Firefox 131.0

Add `https://secure.veritycu.com/veritycu/uux.aspx` to Site Preferences and enable Improved Input Field Detection for it. The password input is inside Shadow DOM and we ignore a bunch of costly DOM parsing by default.

**Comment by icamps** [comment]
> Make sure your extension is updated, this was fixed in version 1.9.2

The extension is up-to-date, but it works when it wants.

> Selecting the field manually using Custom Login Fields also removes that restriction.

Yes, I did that.

**Comment by varjolintu** [comment]
> > Make sure your extension is updated, this was fixed in version 1.9.2
> 
> The extension is up-to-date, but it works when it wants.
> 
> > Selecting the field manually using Custom Login Fields also removes that restriction.
> 
> Yes, I did that.

What is that site you are using?

**Comment by icamps** [comment]
> What is that site you are using?

Is this: [https://sei.unifal-mg.edu.br](https://sei.unifal-mg.edu.br/sip/login.php?sigla_orgao_sistema=Unifal-MG&sigla_sistema=SEI)

**Comment by varjolintu** [comment]
> > What is that site you are using?
> 
> Is this: [https://sei.unifal-mg.edu.br](https://sei.unifal-mg.edu.br/sip/login.php?sigla_orgao_sistema=Unifal-MG&sigla_sistema=SEI)

Could not reproduce after selecting the fields with Custom Login Fields:
<img width="495" alt="Screenshot 2024-10-03 at 18 11 49" src="https://github.com/user-attachments/assets/2b4ce8ca-465c-4bca-b156-d4b0b109fdbd">

**Comment by patja** [comment]
> > > > Not fixed for login fields on [Verity Credit Union](https://secure.veritycu.com)
> > > > Cannot select fields for custom login fields. The confirm button is never enabled when selecting custom login fields.
> > > 
> > > 
> > > Are you sure this is related to this thread?
> > 
> > 
> > No I'm not sure. Maybe it is different because I never see any error message about plain text fields. I do know that nothing happens when I select "Fill Password Only", and I am also unable to specify any custom login fields for this site. My only option is to manually copy and paste the password.
> > KeePassXC - 2.7.9 KeePassXC-Browser - 1.9.3 Operating system: Win64 Browser: Mozilla Firefox 131.0
> 
> Add `https://secure.veritycu.com/veritycu/uux.aspx` to Site Preferences and enable Improved Input Field Detection for it. The password input is inside Shadow DOM and we ignore a bunch of costly DOM parsing by default.

Thank you, this resolved my problem!
