### ISSUE TITLE
Injecting passkey js seemingly breaks Google Spreadsheet sidebar

### ISSUE THREAD

**Issue by CrendKing** [keepassxreboot/keepassxc-browser#2580]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

I have a Apps Script for a Google Spreadsheet, that loads sidebar on open. The content of the sidebar HTML just contains some CSS and buttons. 

I vaguely remember since several months ago, the sidebar starts to intermittently be empty. If I reload the page again, it could randomly be empty again, or load fine. The Apps Script execution history would always show the function be completed successfully. I found that if I either disable KB in Firefox, or just disable "Enable passkeys", the sidebar always loads fine.

I have https://docs.google.com/ completely disabled in the Site Preferences. (The reason I disable docs.google.com is because KB would change title when I open specific spreadsheets if the "Automatically fill in single TOTP entries" is enabled, but I guess that's for [another issue](https://github.com/keepassxreboot/keepassxc-browser/issues/2581).) I can see the passkey js is still injected to the sidebar iframe anyways. Maybe somehow that disrupts the sidebar loading? Is it possible to not inject the script to ignored sites?

Here is how the HTML of the sidebar portion looks like when it is empty:

![Image](https://github.com/user-attachments/assets/a82c0a81-81f9-468f-b607-88092fe012ad)

### Expected Versus Actual Behavior

Expect the sidebar always loads fine.

Actually the sidebar fails to load **randomly**.

### Steps to Reproduce

1. Create a Google Spreadsheet.
2. Create Apps Script for it. Write function to load HTML and open sidebar. Put it on trigger when document is opened.
3. Make sure KB's passkey feature is enable.
4. Notice sometimes sidebar is empty.

Sample script:
```javascript
function loadSidebar() {
  const sidebar = HtmlService.createHtmlOutputFromFile('sidebar')
  SpreadsheetApp.getUi().showSidebar(sidebar)
}
```

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.10
KeePassXC-Browser - 1.9.8
Operating system: Win64
Browser: Mozilla Firefox 139.0
```

**Comment by droidmonkey** [comment]
Is the sidebar stuff loaded from docs.google.com?

**Comment by CrendKing** [comment]
> Is the sidebar stuff loaded from docs.google.com?

Apparently the src of the iframe is https://<random_code>-0lu-script.googleusercontent.com/userCodeAppPanel. But even if add all these 3 to ignore I can still see the passkey js in the iframe:

* https://google.com/
* https://docs.google.com/
* https://googleusercontent.com/

I can also see the "This site is ignored in Site Preferences." message printed 3 times in the console log (coming from `passkeys-inject.js:103:17`).

> the sidebar was never empty

As I noted, this only appears to me randomly. I can't figure out how to repro reliably. But it is not that random (like 1:1 ratio).

**Comment by Hector-wrong** [comment]
> > Is the sidebar stuff loaded from docs.google.com?
> 
> Apparently the src of the iframe is `https://<random_code>-0lu-script.googleusercontent.com/userCodeAppPanel`. But even if add all these 3 to ignore I can still see the passkey js in the iframe:
> 
> * https://google.com/
> * https://docs.google.com/
> * https://googleusercontent.com/
> 
> I can also see the "This site is ignored in Site Preferences." message printed 3 times in the console log (coming from `passkeys-inject.js:103:17`).
> 
> > the sidebar was never empty
> 
> As I noted, this only appears to me randomly. I can't figure out how to repro reliably. But it is not that random (like 1:1 ratio). Disabling passkey reliably solves the issue tho.





https://norman-liberal.github.io/percy5/

**Comment by CrendKing** [comment]
Not sure what are you replying to. But I managed to figure out why my previous attempt to ignore the iframe failed.

As I mentioned above, the src of the iframe is `https://<random_code>-0lu-script.googleusercontent.com/userCodeAppPanel`. And when adding site to ignore list, KeepassXC-Browser does not allow the [Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) (i.e. `https://*.googleusercontent.com/`, complains it is not a valid URL). However, based on the [site matching logic](https://github.com/keepassxreboot/keepassxc-browser/blob/bb1da8c64d63cc184161eaf4f87460849abac4fc/keepassxc-browser/common/global.js#L109-L156), there is way to enable wildcard in hostname, by using `1kpxcwc1` instead of `*`, as the logic will replace that keyword with `.*?` before matching. Unfortunately, since this is undocumented in the Site Preferences page, I'm assuming user should not rely on this mechanism at all.

I think there are three options to solve this problem.

1. Add new option which mimics content scripts' [all_frames](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#all_frames) option. The current and default behavior is basically `true`, where all frames in the page are independently subject to the Site Preferences list. If user set to false, only the top-most frame is checked, and if it is ignored, all frames in that page are ignored.
2. Since the path part of the Site Preference URL allows `*`, why not extend it to the hostname part too? Basically make it Match patterns compatible.
3. If neither can be done, at least make the `1kpxcwc1` officially documented and supported.

**Comment by varjolintu** [comment]
> As I mentioned above, the src of the iframe is `https://<random_code>-0lu-script.googleusercontent.com/userCodeAppPanel`. And when adding site to ignore list, KeepassXC-Browser does not allow the [Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) (i.e. `https://*.googleusercontent.com/`, complains it is not a valid URL).

The extension allows match patterns like that,  but Firefox handles them differently and doesn't allow URL input fields to use wildcard for the subdomain. With Chromium-based browsers it works fine. See: https://github.com/keepassxreboot/keepassxc-browser/issues/1612. We should probably discard the URL type for that input field and do the validation some other way.

**Comment by CrendKing** [comment]
Looking forward to either a fix from Firefox or new valid from you guys.

**Comment by varjolintu** [comment]
This should be fixed now, yes?

**Comment by CrendKing** [comment]
Was there any change towards this issue? I just tested and the issue remains. I still have to Disable all features on `https://1kpxcwc1.googleusercontent.com/`

**Comment by varjolintu** [comment]
> Was there any change towards this issue? I just tested and the issue remains. I still have to Disable all features on `https://1kpxcwc1.googleusercontent.com/`

Yes. I thought https://github.com/keepassxreboot/keepassxc-browser/pull/2757 would affect to this bug as well.

**Comment by CrendKing** [comment]
I can confirm the injected <script> with the passkey.js is no longer there, but the sidebar content still remains empty. I guess the root cause is something else.

If no one is able to reproduce the issue though (or care enough), I'm content with the workaround. Feel free to close.
