### ISSUE TITLE
Defining custom login fields is not working with multiple login pages with the same URL

### ISSUE THREAD

**Issue by masscream** [keepassxreboot/keepassxc-browser#999]
I use this to login to my Internet Banking, where on one page they want me to fill in login (username-only), after that, confirm my date of birth (custom defined fields) and after that the password (must say hell of a way of logining somewhere, so keepassxc makes it a lot of easier, thank you!) 

## Current Behavior
Custom entries for the webpage after firefox addon upgrade are wiped out and can't be re-defined, anytime I define them and hit confirm, they are not saved. Login does not work then.

## Possible Solution
So far, downgrading the addon to 1.6.6 worked.

## Steps to Reproduce (for bugs)
not sure, you would have to have the AirBank account (Czech Republic) to complete the login process, but you may try anyway
1. load https://ib.airbank.cz/
2. enter any username "test" and hit Pokracovat
3. on the next page, test if your addon can fill in custom defined fields (after defining them)...
4. you probably won't make it to the last screen for password since you don't have the account. doesn't matter, there is not the issue.

Thanks!

**Comment by varjolintu** [comment]
Fixed it. Getting the ID for the elements was too simple so username and password field couldn't be distinquished. I also discovered that when using Custom Login Fields, the variables were accidentally overridden temporarily which caused the Custom Fields to go empty when actually there were input fields defined.

**Comment by masscream** [comment]
OK thank you. Great job!

**Comment by masscream** [comment]
I've just tested the version 1.7.1 and must say - it's still not working. Upgrading disables any recognition of the saved database entry and does not provide nor username nor custom login fields on the next page (when inputed manually). Is this a normal way to work? I mean I haven't tried deleting the entry and creating it from scratch, but imho the entry should sustain the upgrade working... Which reminds me making the same/similar mess during the addon downgrade, because I need to define all the settings of the addon from the scratch again, including database auth. I'm keeping the version 1.6.6 since it's the last one working.

**Comment by varjolintu** [comment]
Sadly the old Custom Fields stored to the extension might not work anymore. I suggest you try doing it from scratch.

**Comment by drujd** [comment]
Same problem here - still not working in 1.7.1. Deleting all custom fields and creating them again in the new version does not help.

**Comment by Tabuu** [comment]
The issue for me it seems is that when selecting the fields, there is no way to hide the overlay so that you can go to the next page of the login.

E.g. on one particular page I have to enter my password and username, then click next to enter my TOTP. While this plugin did detect the username and password field, it could not detect the TOTP field.

I tried to custom select the fields, but could not hide the selection overlay. So I could not select the TOTP field on the next page. When restarting the selection process on the second page, it would override the others.

If I may be as bold as to make a suggestion: a context menu item that allows you to select the custom field without overriding the others would be great.

Thank you for the great plugin!

P.S.
One point of interest might be that the TOTP field was detected as the username field right after custom selection. This might have to do with the way the detected fields are stored. I have not looked at the code yet, but I am guessing you are using the index of the field rather than the id/class/other attribute (which as stated above would not work quite well).

**Comment by varjolintu** [comment]
Already a feature request here: #670.
